import { describe, expect, it } from 'vitest';
import {
    erDiagramToSql,
    isErDiagram,
    parseErDiagram,
    sqlType,
} from './erToSql';

const TEMPLATE = `erDiagram
  USER ||--o{ NOTE : writes
  USER {
    int id PK
    string email
  }
  NOTE {
    int id PK
    int user_id FK
    string title
  }`;

describe('isErDiagram', () => {
    it('knows an erDiagram from other diagrams', () => {
        expect(isErDiagram(TEMPLATE)).toBe(true);
        expect(isErDiagram('%% schema\nerDiagram\n  A ||--o{ B : has')).toBe(
            true,
        );
        expect(
            isErDiagram('---\ntitle: Shop\n---\nerDiagram\n  A {\n  }'),
        ).toBe(true);
        expect(isErDiagram('flowchart TD\n  A --> B')).toBe(false);
        expect(isErDiagram('')).toBe(false);
    });
});

describe('parseErDiagram', () => {
    it('reads entities, attributes and relationships', () => {
        const diagram = parseErDiagram(TEMPLATE);

        expect([...diagram.entities.keys()]).toEqual(['USER', 'NOTE']);
        const note = diagram.entities.get('NOTE')!;
        expect(note.attributes.map((a) => a.name)).toEqual([
            'id',
            'user_id',
            'title',
        ]);
        expect([...note.attributes[1].keys]).toEqual(['FK']);
        expect(diagram.relationships).toEqual([
            {
                left: 'USER',
                right: 'NOTE',
                leftCard: { min: 1, many: false },
                rightCard: { min: 0, many: true },
                label: 'writes',
            },
        ]);
    });

    it('reads aliases, quoted names, word cardinalities, keys and comments', () => {
        const diagram = parseErDiagram(`erDiagram
  p[Person] {
    string email PK, UK "login, not null"
  }
  "Line Item"
  p one or more optionally to zero or many "Line Item" : "buys from"`);

        expect(diagram.entities.get('p')!.label).toBe('Person');
        const email = diagram.entities.get('p')!.attributes[0];
        expect([...email.keys]).toEqual(['PK', 'UK']);
        expect(email.comment).toBe('login, not null');
        expect(diagram.entities.has('Line Item')).toBe(true);
        expect(diagram.relationships[0]).toMatchObject({
            left: 'p',
            right: 'Line Item',
            leftCard: { min: 1, many: true },
            rightCard: { min: 0, many: true },
            label: 'buys from',
        });
    });
});

describe('sqlType', () => {
    it('maps Mermaid types per dialect and passes unknown ones through', () => {
        expect(sqlType('string', 'postgres')).toBe('VARCHAR(255)');
        expect(sqlType('varchar(64)', 'mysql')).toBe('VARCHAR(64)');
        expect(sqlType('string', 'sqlite')).toBe('TEXT');
        expect(sqlType('uuid', 'mysql')).toBe('CHAR(36)');
        expect(sqlType('json', 'postgres')).toBe('JSONB');
        expect(sqlType('string[]', 'postgres')).toBe('VARCHAR(255)[]');
        expect(sqlType('datetime', 'postgres')).toBe('TIMESTAMP');
        expect(sqlType('geometry', 'postgres')).toBe('GEOMETRY');
    });
});

describe('erDiagramToSql', () => {
    it('turns the ER template into PostgreSQL', () => {
        expect(erDiagramToSql(TEMPLATE, 'postgres')).toBe(
            `-- Generated from a Mermaid erDiagram (PostgreSQL)

CREATE TABLE "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255)
);

CREATE TABLE note (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    title VARCHAR(255),
    -- USER writes NOTE
    FOREIGN KEY (user_id) REFERENCES "user" (id)
);
`,
        );
    });

    it('speaks each dialect', () => {
        const mysql = erDiagramToSql(TEMPLATE, 'mysql');
        expect(mysql).toContain('CREATE TABLE `user` (');
        expect(mysql).toContain('id INT AUTO_INCREMENT PRIMARY KEY');

        const sqlite = erDiagramToSql(TEMPLATE, 'sqlite');
        expect(sqlite).toContain('id INTEGER PRIMARY KEY,');
        expect(sqlite).toContain('email TEXT');
    });

    it('creates referenced tables first, whatever order they are drawn in', () => {
        const sql = erDiagramToSql(`erDiagram
  ORDER_LINE }o--|| ORDER : "belongs to"
  ORDER }o--|| CUSTOMER : places
  ORDER_LINE { int id PK }
  ORDER { int id PK }
  CUSTOMER { int id PK }`);

        const at = (name: string) => sql.indexOf(`CREATE TABLE ${name} (`);
        expect(at('customer')).toBeLessThan(at('"order"'));
        expect(at('"order"')).toBeLessThan(at('order_line'));
    });

    it('adds the key column a relationship needs when none is drawn', () => {
        const sql = erDiagramToSql(`erDiagram
  TEAM ||--o{ PLAYER : has
  TEAM { uuid id PK }
  PLAYER { int id PK }`);

        expect(sql).toContain(
            'team_id UUID NOT NULL, -- added: TEAM has PLAYER',
        );
        expect(sql).toContain('FOREIGN KEY (team_id) REFERENCES team (id)');
    });

    it('leaves the key nullable when the parent is optional', () => {
        const sql = erDiagramToSql(`erDiagram
  DEPARTMENT |o--o{ EMPLOYEE : employs
  DEPARTMENT { int id PK }
  EMPLOYEE {
    int id PK
    int department_id FK
  }`);

        expect(sql).toMatch(/department_id INTEGER,\n/);
    });

    it('gives one-to-one a unique key on the side that names the other', () => {
        const sql = erDiagramToSql(`erDiagram
  PROFILE ||--|| USER : "belongs to"
  USER { int id PK }
  PROFILE {
    int id PK
    int user_id FK
  }`);

        expect(sql).toContain('user_id INTEGER NOT NULL UNIQUE');
        expect(sql).toContain('FOREIGN KEY (user_id) REFERENCES "user" (id)');
    });

    it('turns many-to-many into a join table', () => {
        const sql = erDiagramToSql(`erDiagram
  STUDENT }o--o{ COURSE : "enrolls in"
  STUDENT { int id PK }
  COURSE { int id PK }`);

        expect(sql).toContain(`-- added: many-to-many, STUDENT enrolls in COURSE
CREATE TABLE student_course (
    student_id INTEGER,
    course_id INTEGER,
    PRIMARY KEY (student_id, course_id),
    FOREIGN KEY (student_id) REFERENCES student (id),
    FOREIGN KEY (course_id) REFERENCES course (id)
);`);
    });

    it('points a self-relationship at its own table', () => {
        const sql = erDiagramToSql(`erDiagram
  EMPLOYEE |o--o{ EMPLOYEE : manages
  EMPLOYEE {
    int id PK
    int manager_id FK
  }`);

        expect(sql).toContain('manager_id INTEGER,');
        expect(sql).toContain(
            'FOREIGN KEY (manager_id) REFERENCES employee (id)',
        );
    });

    it('follows a key named for a table it has no line to', () => {
        const sql = erDiagramToSql(`erDiagram
  AUTHOR { int id PK }
  BOOK {
    int id PK
    int author_id FK
    int shelf_id FK
  }`);

        expect(sql).toContain('FOREIGN KEY (author_id) REFERENCES author (id)');
        expect(sql).toContain(
            'shelf_id INTEGER, -- FK: target not in the diagram',
        );
    });

    it('reads not null, default and references from comments', () => {
        const sql = erDiagramToSql(`erDiagram
  ACCOUNT { int id PK }
  POST {
    int id PK
    int owner FK "references ACCOUNT.id"
    string status "not null, default 'draft'"
  }`);

        expect(sql).toContain("status VARCHAR(255) NOT NULL DEFAULT 'draft',");
        expect(sql).toContain('FOREIGN KEY (owner) REFERENCES account (id)');
        expect(sql).not.toContain('-- references');
    });

    it('keeps the rest of a comment as a comment', () => {
        const sql = erDiagramToSql(`erDiagram
  USER {
    int id PK
    string email UK "login, not null"
  }`);

        expect(sql).toContain('email VARCHAR(255) NOT NULL UNIQUE -- login');
    });

    it('closes a cycle with ALTER TABLE, except in SQLite', () => {
        const source = `erDiagram
  A ||--o{ B : has
  B ||--o{ A : has
  A { int id PK }
  B { int id PK }`;

        expect(erDiagramToSql(source, 'postgres')).toMatch(
            /\nALTER TABLE \w+ ADD FOREIGN KEY \(\w+\) REFERENCES \w+ \(id\);\n$/,
        );
        expect(erDiagramToSql(source, 'sqlite')).not.toContain('ALTER TABLE');
    });

    it('refuses what it cannot turn into tables', () => {
        expect(() => erDiagramToSql('flowchart TD\n  A --> B')).toThrow();
        expect(() => erDiagramToSql('erDiagram')).toThrow();
    });
});
